### ISSUE TITLE
Cliff 1 root cause: FA2 softmax_lse padded by max_seqlen — Genesis-style clamp feasible?

### ISSUE THREAD

**Issue by noonghunna** [Sandermage/genesis-vllm-patches#11]
## Summary

Diagnosed **Cliff 1** root cause to FA2's `softmax_lse` being padded by `max_seqlen`, not by actual `cu_seqlens`. Asking whether a Genesis-style text-patch clamping `attn_metadata.max_seq_len` to the current chunk's actual seqlen at the FA call site is feasible.

Cross-rig context: this is the same Cliff 1 you helped debug in [single-3090#1](https://github.com/noonghunna/qwen36-27b-single-3090/issues/1), where PN8 closes it on `tools-text.yml` (FP8+MTP@75K) but not on TQ3 paths (`long-vision.yml` 192K, `long-text.yml` 205K).

## What we bisected on RTX 3090 + Genesis 917519b (v7.62.x), 2026-04-29

Two configs with **identical boot stats** behave differently on the same 25K-token tool prefill:

| Config | Boot VRAM | KV pool | 25K tool prefill |
|---|---|---|---|
| 48K + 0.92 + TQ3 + vision (default) | 20.8 GB used, 1.87 GiB KV / 148K tok | Cliff 1 ✅ passes |
| 86K + 0.92 + TQ3 + vision (engine ceiling) | 20.8 GB used, 1.87 GiB KV / 148K tok | Cliff 1 ❌ fails |

Same idle VRAM, same KV pool size, same Genesis patches, same prompt. The only difference is `max_model_len`. OOM signature:

```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB.
GPU 0 has a total capacity of 23.56 GiB of which 30.50 MiB is free.
22.67 GiB allocated, 24 MiB in private pools, 508 MiB reserved but unallocated.

  File ".../vllm/v1/attention/backends/turboquant_attn.py", line 855, in _continuation_prefill
    return self._flash_attn_varlen(
  File ".../vllm/v1/attention/backends/turboquant_attn.py", line 340, in _flash_attn_varlen
    return flash_attn_varlen_func(
  File ".../vllm_flash_attn/flash_attn_interface.py", line 300, in flash_attn_varlen_func
    out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(...)
```

## Root cause (with vLLM source citation, h/t ChatGPT review)

FA2's `varlen_fwd` allocates `softmax_lse` as `[num_seqs, num_heads, max_seqlen]` — sized by the `max_seqlen` parameter, NOT by the actual `cu_seqlens` ([upstream FA issue Dao-AILab/flash-attention#1011](https://github.com/Dao-AILab/flash-attention/issues/1011), open since 2024).

vLLM passes `attn_metadata.max_seq_len` through to that call. During cudagraph capture, [`gpu_model_runner` sets `max_seq_len = self.max_model_len`](https://docs.vllm.ai/en/latest/api/vllm/v1/worker/gpu_model_runner/) for shape stability. So at `max-model-len=86K`, even a 25K-token chunk reserves softmax_lse for 86K, eating the activation headroom that 48K's smaller leaked workspace would leave free.

[vllm#40961](https://github.com/vllm-project/vllm/pull/40961) (open PR, "Preserve max_seq_len in ubatch metadata during CUDA graph capture") confirms this is the established pattern — that PR is *fixing* a SWA case where `seqlen=1` at capture broke kernel selection by *adding* the `max_model_len` pass-through. So we can't just remove the cap-leak; capture metadata genuinely needs it for shape stability.

## Why PN8 closes Cliff 1 on tools-text but not on long-vision

PN8 frees ~900 MiB of draft-model VRAM on FP8+MTP. At 75K (tools-text), the leaked `softmax_lse[:,:, 75000]` is small enough (~50-100 MiB) that PN8's freed headroom absorbs it cleanly. At 192K (long-vision), the leak is ~200-300 MiB — bigger than PN8's gain, and PN8 doesn't apply on TQ3 anyway (different mechanism path, KV-format-not-weight-quant).

So PN8 is "give enough headroom to absorb the leak when it's small enough." It works on tools-text and stops working at 100K+ ctx.

## Question for Genesis: clamp `max_seq_len` at the FA call site?

Conceptually, in the prefill (non-capture) path, `max_seq_len` *could* be set to `(cu_seqlens[1:] - cu_seqlens[:-1]).max()` instead of `max_model_len`. That would size `softmax_lse` for the actual longest sequence in the batch — same kernel-shape predictability, much smaller workspace.

Constraints I see:
- **Capture-time path needs the cap** (per vllm#40961's reasoning). So a clamp would have to be runtime-only, not capture-time.
- **SWA models** rely on `max_model_len` flowing through correctly (vllm#40961 fix). Clamp can't break that.
- **Paged KV** — current_seqlen for varlen with paged KV needs to be the actual value, which is what we'd compute anyway.

Is this text-patch-friendly in the same vein as your P3/P4/P5/P6 series — patch the `_flash_attn_varlen` call site in `turboquant_attn.py` (or upstream `vllm/v1/attention/backends/flash_attn.py`) to substitute `current_max` for `metadata.max_seq_len` in the prefill path? Or does the cudagraph capture machinery prevent that without deeper changes?

If feasible: would close Cliff 1 on TQ3 paths *structurally* rather than via the absorb-the-leak strategy. If infeasible: status quo (default 48K + tools-text 75K + PN8) remains the right ceiling and we'll wait on Dao-AILab/flash-attention#1011.

We've documented this in our [docs/UPSTREAM.md](https://github.com/noonghunna/club-3090/blob/master/docs/UPSTREAM.md) and [docs/FAQ.md "what's a prefill cliff"](https://github.com/noonghunna/club-3090/blob/master/docs/FAQ.md#whats-a-prefill-cliff). Earlier "FFN intermediate buffer at 138 MiB" characterization was wrong — empirical OOM site is consistently `_vllm_fa2_C.varlen_fwd`.

Happy to provide more bench data or run patch candidates on our 3090 + 2× 3090 rigs. Take your time — no rush. Thanks for everything you've shipped.

**Comment by noonghunna** [comment]
## Update: Cliff 1 has TWO mechanisms; P101 reroutes around one but exposes the other

Tested **P101 + P103 enabled** on `long-vision.yml` and `long-text.yml` configs on RTX 3090, expecting Cliff 1 to close. Result: **P101 + P103 confirmed apply correctly, but Cliff 1 still fires** — with a different OOM site than what we'd been observing on stock long-vision.

Three runs, all with `GENESIS_ENABLE_P101=1 GENESIS_ENABLE_P103=1` + your default Genesis stack (P3/P4/P5/P6/P64/P65/P66/etc.):

| Config | OOM site | Allocate / Free at fault |
|---|---|---|
| 192K + 0.98 + TQ3 + **vision** | FFN intermediate buffer | 138 MiB / 130 MiB |
| 175K + 0.97 + TQ3 + **vision** | FFN intermediate buffer | 138 MiB / 110 MiB |
| 205K + 0.98 + TQ3 + **no-vision** | FA2 `softmax_lse` (varlen_fwd) | 50 MiB / 50 MiB |

The FFN buffer site is the inductor-compiled `up_proj` output:

```
File ".../inductor_cache/y2/cy2xsshrxipfsjh7fnewyrswzxpquvqp6fz4pbyhrphxbland3n6.py", line 1208, in call
    buf9 = empty_strided_cuda((s18, 17408), (17408, 1), torch.float16)
```

`s18 = max_num_batched_tokens = 4128` (can't go below that on hybrid because of Mamba `block_size` constraint), `17408 = intermediate_size` for Qwen3.6-27B → `4128 × 17408 × 2 bytes ≈ 138 MiB`. This is the FFN's up-proj activation, allocated per chunked-prefill batch.

**So the picture:**

1. **WITHOUT P101**, continuation prefill at long ctx → FA2 path → `softmax_lse` cap-leak (sized by `attn_metadata.max_seq_len = max_model_len`) → 50–138 MiB OOM at FA2 site (this is the case my [issue #11](https://github.com/Sandermage/genesis-vllm-patches/issues/11) describes).

2. **WITH P101**, continuation prefill reroutes through TQ decode kernel for long-cached-prefix → bypasses FA2 → but the FFN intermediate buffer (`up_proj` output, sized by `max_num_batched_tokens × intermediate_size`) is the next-largest activation and now fires Cliff 1 instead.

3. **Vision tower (~500 MiB)** is the swing — with vision, FFN buffer clears the threshold first; without vision, FA2 softmax_lse clears it first.

**P103 works as advertised** — applied cleanly, would close Cliff 2 (didn't test the 50–60K single-prompt case directly here since these tests were on Cliff 1 reproduction). Stack trace doesn't show fla.ops anywhere.

### What this means for the issue #11 ask

The clamp at the FA call site (max_seqlen_k → actual current chunk) would still close the FA2 softmax_lse mechanism (Cliff 1 case 1 above). On `tools-text.yml` (75K, FP8, no Genesis cliff routing) this is what closes Cliff 1 today via PN8's headroom absorption.

**But on TQ3 long-ctx paths (long-vision/long-text), the FA2 clamp alone wouldn't be sufficient** — even after, the FFN buffer mechanism still fires. That's a separate problem in inductor-compiled FFN codegen. Possible mitigations:

- Smaller per-step activation: requires `max_num_batched_tokens < 4128` which is blocked by Mamba block_size on hybrid (asserted at boot).
- Activation checkpointing in FFN forward: requires upstream FFN module changes.
- Drop vision tower: frees ~500 MiB and shifts the dominant cliff back to FA2 softmax_lse (which the clamp would then close).

So a complete TQ3 long-ctx fix is roughly: **FA2 clamp + drop vision tower (or some equivalent ~500 MiB freeing)**. Or: **FA2 clamp + chunked FFN forward** which is much harder.

For our shipped configs, this means the practical envelope after a hypothetical clamp is:

| Workload | Path |
|---|---|
| IDE agent (tools, mid-ctx ≤75K) | `tools-text.yml` (FP8 + PN8 + clamp would compose cleanly) ✅ |
| Long-text-no-vision frontier (≤205K) | `long-text.yml` + clamp → would close FA2 softmax_lse mechanism, becomes cliff-1-safe for big tool returns ✅ |
| Long-vision frontier (≤192K) | `long-vision.yml` + clamp → still fires FFN buffer cliff ❌ unchanged |

So even the clamp doesn't fully unlock long-vision, but it does meaningfully widen the safe envelope for long-text. Worth shipping if feasible.

### Composability data point

P101 + P103 + the rest of your default stack composed cleanly across all three test configs. No anchor drift, no apply errors. Boot stats:

- 192K + 0.98 + vision: 22.0 GB used at boot, KV pool 260K tok / 3.28 GiB
- 175K + 0.97 + vision: 22.0 GB used at boot, KV pool 240K tok / 3.05 GiB
- 205K + 0.98 + no-vision: 21.5 GB used at boot, KV pool 268K tok / 3.42 GiB

P101's threshold-lowering and 64-token slicing applied without errors. Confirmed via apply_all log.

### TL;DR for you

- P101 works for what it does (reroutes around FA2 softmax_lse path on long-cached-prefix continuation prefill). 
- P103 works (Cliff 2 mitigation). 
- The Cliff 1 we were chasing has dual mechanisms; P101 closes one, the FFN buffer closes the other. 
- The clamp asked for in issue #11 still useful for the FA2 path — particularly on `long-text` no-vision configs where the FFN buffer doesn't dominate.

No urgency on this. Just wanted to share the cross-rig data while the diagnosis is fresh. We'll keep `default` capped at 48K and `tools-text` capped at 75K. Tier 2 work for us; rest well.

**Comment by noonghunna** [comment]
**Update from cross-rig testing (2026-04-30 PM):**

Since filing this, we found Cliff 1 has two mechanisms on TQ3+single-card:
- **Mech A** — FA2 `softmax_lse` cap-leak (what this issue asks about)
- **Mech B** — FFN intermediate buffer (`SiluAndMul` output, ~138 MiB at 4128-token chunks)

PN12 was *intended* to close mech B, but on dev205+ its anchor was silently no-op'd (same class as P101). Once PN12 actually applies, **mech B closes and the 205K Cliff 1 tool-prefill OOM goes away** on RTX 3090 single-card with `--num-gpu-blocks-override 50` + Genesis stack — verify-full + verify-stress pass, MTP AL 2.45. The PN12 anchor fix is in #13.

So the answer to "is Cliff 1 the FA2 cap-leak?" turned out to be: it's BOTH, and on TQ3 mech B was the binding constraint. With anchor-fixed PN12 the cliff effectively closes without needing a Genesis-side FA2 clamp on this stack.

**On the FA2 clamp question itself:** we built a local P104 sidecar (`GENESIS_ENABLE_FA_MAX_SEQLEN_CLAMP=1`, env-gated, runtime-only, never under-clamps) for defensive coverage of mech A. We're holding it from a PR because it's new functionality rather than an anchor fix — happy to PR if you want it in Genesis, or to keep it local-only if Genesis should stay narrowly scoped here. Not blocking either way.

Feel free to close this issue if PR #13 is a sufficient resolution.

**Comment by Sandermage** [comment]
Resolved in v7.64 — PN17 ([patch_N17_fa2_softmax_lse_clamp.py](https://github.com/Sandermage/genesis-vllm-patches/blob/main/vllm/_genesis/wiring/kv_cache/patch_N17_fa2_softmax_lse_clamp.py)).

Implementation in response to your cross-rig diagnosis (RTX 3090, 2026-04-29). The fix replaces `max_seqlen_k = attn_metadata.max_seq_len` with runtime clamp to actual `seqused_k.max()` when CUDA stream is not capturing — frees 50-100 MiB on long-context FA2.

Credit for the root-cause analysis is yours. Genesis just turned the sidecar workaround into a proper anchored text-patch with the cudagraph capture guard. Closing.

Env: `GENESIS_ENABLE_PN17_FA2_LSE_CLAMP=1`. Empirically verified neutral TPS on 35B (-1.9% NS in our bench), free memory headroom realized.
